export * from './auth';
export * from './patient';
export * from './invoice';
export * from './protocol';
export * from './appointment';
export * from './inventory';
export * from './user';
export * from './supplier';
export * from './paymentMethod'; 